name: Deploy Website

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS Credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::108782075355:role/GitHubActionsS3DeployRole
          aws-region: ap-south-1

      - name: Deploy to S3
        run: |
          aws s3 sync . s3://paani-foundation-website-cicd --delete --acl public-read
